services:
  run_date:
    image: abildaev/run_date
    build:
      dockerfile: date.dockerfile
    environment:
      - DOCKER_BUILDKIT=0  # Исправленная строка

  run_index:
    image: abildaev/run_index
    build:
      dockerfile: index.dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - run_date