services:
  run_date:
    image: abilldaev/run_date
    build:
      dockerfile: date.dockerfile
    ports:
      - "3005:3005"
  run_index:
    image: abilldaev/run_index
    build:
      dockerfile: index.dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - run_date
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
      - ./certbot/www:/var/www/certbot
      - ./certbot/data:/etc/letsnecrypt
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/data:/etc/letsnecrypt